parameters:
    upload_directory: '%kernel.project_dir%/public/uploads'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\Service\:
        resource: '../src/Service/'

    App\Repository\:
        resource: '../src/Repository/'

    App\EventListener\:
        resource: '../src/EventListener/'
        tags: ['kernel.event_listener']

    App\MessageHandler\:
        resource: '../src/MessageHandler/'
        tags: ['messenger.message_handler']
